#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 0d9037f2-d15d-464f-9460-edfc2f903d16
# Source File: C:\Users\Poi\Documents\SAPIEN\PowerShell Studio\Files\Scanner.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.160
     Generated on:       03/07/2019 10:57
     Generated by:       Poi
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2019
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Scanner_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$datagrid1 = New-Object 'System.Windows.Forms.DataGrid'
	$listboxMachines = New-Object 'System.Windows.Forms.ListBox'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$fileToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$exitToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$editToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$helpToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$addComputerToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$addFileToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$clearListToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$startScanToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$stopScanToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$pasteToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$copyToClipboardToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$divToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripSeparator'
	$divToolStripMenuItem1 = New-Object 'System.Windows.Forms.ToolStripSeparator'
	$removeSelectedToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$divToolStripMenuItem2 = New-Object 'System.Windows.Forms.ToolStripSeparator'
	$saveScanToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$divToolStripMenuItem3 = New-Object 'System.Windows.Forms.ToolStripSeparator'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$global:scanArray = @()
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	
	$exitToolStripMenuItem_Click={
		#TODO: Place custom script here
		$form1.Close()
	}
	
	$aboutToolStripMenuItem_Click={
		#TODO: Place custom script here
		[System.Windows.Forms.MessageBox]::Show("Menu Application v1.0","Menu Application");
	}
	
	
	
	#region Control Helper Functions
	function Update-ListBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ListBox or CheckedListBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ListBox control.
		
		.PARAMETER ListBox
			The ListBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ListBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
			
		.PARAMETER ValueMember
			Indicates the property to use for the value of the control.
		
		.PARAMETER Append
			Adds the item(s) to the ListBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ListBox $ListBox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ListBox $listBox1 "Red" -Append
			Update-ListBox $listBox1 "White" -Append
			Update-ListBox $listBox1 "Blue" -Append
		
		.EXAMPLE
			Update-ListBox $listBox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ListBox]
			$ListBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]$DisplayMember,
			[Parameter(Mandatory = $false)]
			[string]$ValueMember,
			[switch]
			$Append
		)
		
		if (-not $Append)
		{
			$ListBox.Items.Clear()
		}
		
		if ($Items -is [System.Windows.Forms.ListBox+ObjectCollection] -or $Items -is [System.Collections.ICollection])
		{
			$ListBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ListBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$ListBox.Items.Add($obj)
			}
			$ListBox.EndUpdate()
		}
		else
		{
			$ListBox.Items.Add($Items)
		}
		
		$ListBox.DisplayMember = $DisplayMember
		$ListBox.ValueMember = $ValueMember
	}
	#endregion
	
	Function Show-Inputbox
	{
		Param ([string]$message = $(Throw "You must enter a prompt message"),
			[string]$title = "Input",
			[string]$default
			)
		
		[reflection.assembly]::loadwithpartialname("microsoft.visualbasic") | Out-Null
		[microsoft.visualbasic.interaction]::InputBox($message, $title, $default)
	}
	
	$addFileToolStripMenuItem_Click={
		$openFileDialog = New-Object windows.forms.openfiledialog
		$openFileDialog.initialDirectory = [System.IO.Directory]::GetCurrentDirectory()
		$openFileDialog.title = "Select CSV File to Import"
		$openFileDialog.filter = "CSV Files|*.csv|All Files|*.*"
		$openFileDialog.ShowHelp = $True
		$result = $openFileDialog.ShowDialog()
		$result
		if ($result -eq "OK")
		{
			Import-Csv $OpenFileDialog.filename -Header Machine,Note| ForEach-Object {
				$listboxMachines.Items.Add($_.Machine)
			}
		}
	}
	
	$addComputerToolStripMenuItem_Click = {
		$item = Show-Inputbox -title "Add Computer" -message "Enter Machine:"
		$listboxMachines.Items.Add($item)
	}
	
	$pasteToolStripMenuItem_Click={
		$item = Get-Clipboard -Format Text
		$listboxMachines.Items.Add($item)
	}
	
	$clearListToolStripMenuItem_Click={
		$listboxMachines.Items.Clear()
	}
	
	$removeSelectedToolStripMenuItem_Click={
		for ($items = $listboxMachines.SelectedIndices.Count - 1; $items -ge 0; $items--)
		{
			$item = $listboxMachines.SelectedIndices[$items]
			$listboxMachines.Items.RemoveAt($item)
		}
	}
	
	$copyToClipboardToolStripMenuItem_Click = {
		$item = $listboxMachines.SelectedItem
		Set-Clipboard -Value $item
	}
	
	$saveScanToolStripMenuItem_Click = {
		$saveFileDialog = New-Object -TypeName Windows.Forms.SaveFileDialog
		$saveFileDialog.initialDirectory = [System.IO.Directory]::GetCurrentDirectory()
		$saveFileDialog.title = "Select CSV File to Save"
		$saveFileDialog.FileName = "Output.csv"
		$saveFileDialog.Filter = "CSV Files|*.csv|All Files|*.*"
		$saveFileDialog.ShowHelp = $True
		$saveFileDialog.ShowDialog()
		$global:scanArray | ConvertTo-Csv -NoTypeInformation | Set-Content $saveFileDialog.FileName
	}
	
	$startScanToolStripMenuItem_Click={
		foreach ($item in $listboxMachines.Items)
		{
			$scanItem = New-Object -Type PSObject
			Add-Member -InputObject $scanItem -MemberType NoteProperty -Name "Host" -Value $item
			$global:scanArray += $scanItem
		}
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$form1.remove_Load($form1_Load)
			$exitToolStripMenuItem.remove_Click($exitToolStripMenuItem_Click)
			$aboutToolStripMenuItem.remove_Click($aboutToolStripMenuItem_Click)
			$addComputerToolStripMenuItem.remove_Click($addComputerToolStripMenuItem_Click)
			$addFileToolStripMenuItem.remove_Click($addFileToolStripMenuItem_Click)
			$clearListToolStripMenuItem.remove_Click($clearListToolStripMenuItem_Click)
			$startScanToolStripMenuItem.remove_Click($startScanToolStripMenuItem_Click)
			$pasteToolStripMenuItem.remove_Click($pasteToolStripMenuItem_Click)
			$copyToClipboardToolStripMenuItem.remove_Click($copyToClipboardToolStripMenuItem_Click)
			$removeSelectedToolStripMenuItem.remove_Click($removeSelectedToolStripMenuItem_Click)
			$saveScanToolStripMenuItem.remove_Click($saveScanToolStripMenuItem_Click)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	$menustrip1.SuspendLayout()
	$datagrid1.BeginInit()
	#
	# form1
	#
	$form1.Controls.Add($datagrid1)
	$form1.Controls.Add($listboxMachines)
	$form1.Controls.Add($menustrip1)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '493, 345'
	$form1.MainMenuStrip = $menustrip1
	$form1.Name = 'form1'
	$form1.StartPosition = 'CenterScreen'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# datagrid1
	#
	$datagrid1.DataMember = ''
	$datagrid1.HeaderForeColor = 'ControlText'
	$datagrid1.Location = '139, 28'
	$datagrid1.Name = 'datagrid1'
	$datagrid1.Size = '342, 302'
	$datagrid1.TabIndex = 2
	#
	# listboxMachines
	#
	$listboxMachines.FormattingEnabled = $True
	$listboxMachines.Location = '12, 27'
	$listboxMachines.Name = 'listboxMachines'
	$listboxMachines.SelectionMode = 'MultiExtended'
	$listboxMachines.Size = '120, 303'
	$listboxMachines.TabIndex = 1
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($fileToolStripMenuItem)
	[void]$menustrip1.Items.Add($editToolStripMenuItem)
	[void]$menustrip1.Items.Add($helpToolStripMenuItem)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = 'menustrip1'
	$menustrip1.Size = '493, 24'
	$menustrip1.TabIndex = 0
	$menustrip1.Text = 'menustrip1'
	#
	# fileToolStripMenuItem
	#
	[void]$fileToolStripMenuItem.DropDownItems.Add($addComputerToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($addFileToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($pasteToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($divToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($copyToClipboardToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($divToolStripMenuItem1)
	[void]$fileToolStripMenuItem.DropDownItems.Add($removeSelectedToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($clearListToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($divToolStripMenuItem2)
	[void]$fileToolStripMenuItem.DropDownItems.Add($saveScanToolStripMenuItem)
	[void]$fileToolStripMenuItem.DropDownItems.Add($divToolStripMenuItem3)
	[void]$fileToolStripMenuItem.DropDownItems.Add($exitToolStripMenuItem)
	$fileToolStripMenuItem.Name = 'fileToolStripMenuItem'
	$fileToolStripMenuItem.Size = '37, 20'
	$fileToolStripMenuItem.Text = 'File'
	#
	# exitToolStripMenuItem
	#
	$exitToolStripMenuItem.Name = 'exitToolStripMenuItem'
	$exitToolStripMenuItem.Size = '171, 22'
	$exitToolStripMenuItem.Text = 'Exit'
	$exitToolStripMenuItem.add_Click($exitToolStripMenuItem_Click)
	#
	# editToolStripMenuItem
	#
	[void]$editToolStripMenuItem.DropDownItems.Add($startScanToolStripMenuItem)
	[void]$editToolStripMenuItem.DropDownItems.Add($stopScanToolStripMenuItem)
	$editToolStripMenuItem.Name = 'editToolStripMenuItem'
	$editToolStripMenuItem.Size = '44, 20'
	$editToolStripMenuItem.Text = 'Scan'
	#
	# helpToolStripMenuItem
	#
	[void]$helpToolStripMenuItem.DropDownItems.Add($aboutToolStripMenuItem)
	$helpToolStripMenuItem.Name = 'helpToolStripMenuItem'
	$helpToolStripMenuItem.Size = '44, 20'
	$helpToolStripMenuItem.Text = 'Help'
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = 'aboutToolStripMenuItem'
	$aboutToolStripMenuItem.Size = '152, 22'
	$aboutToolStripMenuItem.Text = 'About'
	$aboutToolStripMenuItem.add_Click($aboutToolStripMenuItem_Click)
	#
	# addComputerToolStripMenuItem
	#
	$addComputerToolStripMenuItem.Name = 'addComputerToolStripMenuItem'
	$addComputerToolStripMenuItem.Size = '171, 22'
	$addComputerToolStripMenuItem.Text = 'Add Computer'
	$addComputerToolStripMenuItem.add_Click($addComputerToolStripMenuItem_Click)
	#
	# addFileToolStripMenuItem
	#
	$addFileToolStripMenuItem.Name = 'addFileToolStripMenuItem'
	$addFileToolStripMenuItem.Size = '171, 22'
	$addFileToolStripMenuItem.Text = 'Add File'
	$addFileToolStripMenuItem.add_Click($addFileToolStripMenuItem_Click)
	#
	# clearListToolStripMenuItem
	#
	$clearListToolStripMenuItem.Name = 'clearListToolStripMenuItem'
	$clearListToolStripMenuItem.Size = '171, 22'
	$clearListToolStripMenuItem.Text = 'Clear List'
	$clearListToolStripMenuItem.add_Click($clearListToolStripMenuItem_Click)
	#
	# startScanToolStripMenuItem
	#
	$startScanToolStripMenuItem.Name = 'startScanToolStripMenuItem'
	$startScanToolStripMenuItem.Size = '152, 22'
	$startScanToolStripMenuItem.Text = 'Start Scan'
	$startScanToolStripMenuItem.add_Click($startScanToolStripMenuItem_Click)
	#
	# stopScanToolStripMenuItem
	#
	$stopScanToolStripMenuItem.Name = 'stopScanToolStripMenuItem'
	$stopScanToolStripMenuItem.Size = '152, 22'
	$stopScanToolStripMenuItem.Text = 'Stop Scan'
	#
	# pasteToolStripMenuItem
	#
	$pasteToolStripMenuItem.Name = 'pasteToolStripMenuItem'
	$pasteToolStripMenuItem.Size = '171, 22'
	$pasteToolStripMenuItem.Text = 'Add Clipboard'
	$pasteToolStripMenuItem.add_Click($pasteToolStripMenuItem_Click)
	#
	# copyToClipboardToolStripMenuItem
	#
	$copyToClipboardToolStripMenuItem.Name = 'copyToClipboardToolStripMenuItem'
	$copyToClipboardToolStripMenuItem.Size = '171, 22'
	$copyToClipboardToolStripMenuItem.Text = 'Copy to Clipboard'
	$copyToClipboardToolStripMenuItem.add_Click($copyToClipboardToolStripMenuItem_Click)
	#
	# divToolStripMenuItem
	#
	$divToolStripMenuItem.Name = 'divToolStripMenuItem'
	$divToolStripMenuItem.Size = '168, 6'
	#
	# divToolStripMenuItem1
	#
	$divToolStripMenuItem1.Name = 'divToolStripMenuItem1'
	$divToolStripMenuItem1.Size = '168, 6'
	#
	# removeSelectedToolStripMenuItem
	#
	$removeSelectedToolStripMenuItem.Name = 'removeSelectedToolStripMenuItem'
	$removeSelectedToolStripMenuItem.Size = '171, 22'
	$removeSelectedToolStripMenuItem.Text = 'Remove Selected'
	$removeSelectedToolStripMenuItem.add_Click($removeSelectedToolStripMenuItem_Click)
	#
	# divToolStripMenuItem2
	#
	$divToolStripMenuItem2.Name = 'divToolStripMenuItem2'
	$divToolStripMenuItem2.Size = '168, 6'
	#
	# saveScanToolStripMenuItem
	#
	$saveScanToolStripMenuItem.Name = 'saveScanToolStripMenuItem'
	$saveScanToolStripMenuItem.Size = '171, 22'
	$saveScanToolStripMenuItem.Text = 'Save Scan'
	$saveScanToolStripMenuItem.add_Click($saveScanToolStripMenuItem_Click)
	#
	# divToolStripMenuItem3
	#
	$divToolStripMenuItem3.Name = 'divToolStripMenuItem3'
	$divToolStripMenuItem3.Size = '168, 6'
	$datagrid1.EndInit()
	$menustrip1.ResumeLayout()
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-Scanner_psf | Out-Null
